# The OpusTrainer config for a student model.
# https://github.com/hplt-project/OpusTrainer?tab=readme-ov-file#configuration-file

datasets:
  original: {dataset0} # Original parallel corpus

stages:
  - train

train:
  - original 1.0
  - until original inf # General training until marian early stops

seed: 1111

# The data is provided in the following format:
# <src_sentence> "\t" <trg_sentence> "\t" <alignments>
num_fields: 3

# See ./teacher.yml for documentation on these properties and how train.py modifies it.
modifiers:
  common:
    - Noise: 0.0005
      min_word_length: 2
      max_word_length: 5
      max_words: 6

    - Tags: 0.005
      augment: 1
      tag: 0
      custom_detok_src: "icu:{src}"
      custom_detok_trg: "icu:{trg}"
      # Student distillation uses guided alignments, so the SentencePiece vocab is used here.
      spm_vocab_src: {vocab_src}
      spm_vocab_trg: {vocab_trg}

    # Remove terminal punctuation to teach the model translate text without it
    - RemoveEndPunct: 0.2

  bicameral_src:
    - UpperCase: 0.07
    - TitleCase: 0.05
  phonemic_src:
    - Typos: 0.05
