experiment:
  name: retrain_base-memory
  src: en
  trg: ar
  best-model: chrf
  opuscleaner-mode: defaults
  bicleaner:
    default-threshold: 0.5
    dataset-thresholds: {}
  monocleaner:
    mono-src:
      default-threshold: 0.0
      dataset-thresholds:
        hplt_mono_v2_0: 0.5
        opus_NLLB_v1: 0.5
    mono-trg:
      default-threshold: 0.0
      dataset-thresholds:
        hplt_mono_v2_0: 0.7
        opus_NLLB_v1: 0.8
  mono-max-sentences-src:
    total: 300_000_000
    per-dataset: 100_000_000
  mono-max-sentences-trg:
    total: 200_000_000
    per-dataset: 100_000_000
  hplt-min-doc-score:
    mono-src: 7.0
    mono-trg: 9.0
  spm-sample-size: 10_000_000
  spm-vocab-size: 32000
  spm-vocab-split: false
  teacher-ensemble: 1
  teacher-mode: two-stage
  teacher-decoder: ctranslate2
  student-model: base-memory
  # Archive corpora from alignments tasks to GCS
  archive-corpora: true
datasets:
  test:
    - flores_devtest
    - flores_aug-mix_devtest
    - flores_aug-title_devtest
    - flores_aug-upper_devtest
    - flores_aug-punct_devtest
    - flores_aug-typos_devtest
    - flores_aug-noise_devtest
    - flores_aug-inline-noise_devtest
    - sacrebleu_iwslt17
    - mtdata_Neulab-tedtalks_test-1-eng-ara
  devtest:
    - mtdata_aug-mix_Neulab-tedtalks_dev-1-eng-ara
    - flores_aug-mix_dev
marian-args:
  decoding-backward:
    beam-size: '12'
    mini-batch-words: '2000'
  decoding-teacher:
    mini-batch-words: '5000'
    maxi-batch: '10000'
  training-backward:
    early-stopping: '5'
  training-teacher:
    early-stopping: '20'
  training-student:
    early-stopping: '15'
  training-student-finetuned:
    early-stopping: '20'
target-stage: all-pipeline
wandb-publication: true
continuation:
  vocab:
    src: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KK4z6NciRRirhvLlQo9C2A/runs/0/artifacts/public%2Fbuild%2Fvocab.spm
    trg: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/KK4z6NciRRirhvLlQo9C2A/runs/0/artifacts/public%2Fbuild%2Fvocab.spm
  corpora:
    distillation:
      src: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/FnYPkc_QS12O6L_waj_jqw/runs/0/artifacts/public%2Fbuild%2Fcorpus.en.zst
      trg: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/FnYPkc_QS12O6L_waj_jqw/runs/0/artifacts/public%2Fbuild%2Fcorpus.ar.zst
      tok-src: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/YIiHBFmUQA-Eb8AIgr1SEA/runs/0/artifacts/public%2Fbuild%2Fcorpus.tok-icu.en.zst
      tok-trg: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/YIiHBFmUQA-Eb8AIgr1SEA/runs/0/artifacts/public%2Fbuild%2Fcorpus.tok-icu.ar.zst
      alignments: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/YIiHBFmUQA-Eb8AIgr1SEA/runs/0/artifacts/public%2Fbuild%2Fcorpus.aln.zst
taskcluster:
  split-chunks: 20
  upload-bucket: production
  worker-classes:
    default: gcp-spot
    corpus-align-parallel: gcp-standard
    corpus-align-backtranslations: gcp-standard
    corpus-align-distillation: gcp-standard
    distillation-corpus-build-shortlist: gcp-standard
